### ISSUE TITLE
Compact post view

### ISSUE THREAD

**Issue by not-matthias** [not-matthias/apollo#32]
I really like the design of @peterkos' posts page. It makes it look very compact and clean. I feel like all the red underlines and hashes are a little distracting.
![image](https://github.com/not-matthias/apollo/assets/26800596/437a4fcf-5cd4-458d-9913-acdff9d1d514)

**Comment by peterkos** [comment]
Aw thanks! I appreciate it :D 

I spent a while playing around with grid (so the `#` are aligned). Since [subgrid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Subgrid#browser_compatibility) isn't fully out yet, [my workaround](https://github.com/peterkos/peterkos.github.io/blob/5ffb217662321cd0dda7b24058b0999b731a260b/sass/custom.scss#L70-L91) was to `display: contents` child elements, so grid would apply to the `.meta` date + title, not just the surrounding `<div>`.
